config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config



  

  get 'home/index'
  root :to => "home#index"  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Jay added the next line.

 
#   get 'about', to: 'static#about'
#  get 'posts', to: 'posts#index'
  resources :posts
  resources :categories
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
#	attr_accessible :name, :body, :cagegory_id, :author_id
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
		#show all posts in this category
		puts "in new category show controller"
		@category = Category.find(params[:id])
		@title = @category.name
  		@allPosts = @category.posts
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all()		
	end

	def show
		@post = Post.find(params[:id])
		@catName = Category.name
		@allPosts = Post.where(cetegory_id: @post.category_id)
	end

	def new
		@post = Post.new
	end
	
	def post_params
		params.require(:post).permit(:id, :title, :body, :category_id)
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, :notice => "Your post was saved"
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to posts_path, :notice => "Your post was edited"
		else
			render "edit"
		end
	end


	def destroy
		@post = Post.find(params[:id])
		@post.delete
		redirect_to posts_path, :notice => "Your post was destroyed"
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
#      render "index"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
  <ul>
    <% @categories.each do |category| %>  
        <li><%= link_to category.name, category %></li>
    <% end %>
  </ul>
<br>

<%= button_to 'New Category', new_category_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<% if @allPosts.length > 0 %>
	<strong> <%= "Existing Posts in " + @category.name + " Category" %></strong></br>
	<% @allPosts.each do |p| %>
		<%= link_to p.title, post_path(p) %> </br>
	<% end %>
<% else %>
	<strong> <%= "There are no Posts in " + @category.name + " Category" %></strong></br>
<% end %>
</br>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Initial home page fo Jayzblog page</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>


	</head>

  <body>
    <% flash.each do |key, value| %>
		<p> <%= value %> </p>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_original.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>in the posts/index</h1>
<% @posts.each do |p| %>
<%= link_to p.title, p %>
<%= p.body %>
<p>
<%= @catName = "Category = " +Category.find(p.category_id).name %>
<hr>
<% end %>
<%= link_to "Create another post" , new_post_path %>

app/views/posts/show.html.erb
<% display = "In Post/show for id = " + @post.id.to_s %>
<h1> <%= display %> </h1>
<p>
<h2> <%= @post.title %> </h2>
<p><%= @post.body %></p>
<%= link_to "Back to " + @post.category.name + " category" , category_path(@post.category_id) %></br>
<%= link_to 'Back', posts_path %>
<p> </p>